DATASETS:
  TRAIN: ("rotated_bbox_train",)
  TEST: ("rotated_bbox_val",)
DATALOADER:
  NUM_WORKERS: 1
MODEL:
  ROI_HEADS:
    NAME: "RROIHeads"
    BATCH_SIZE_PER_IMAGE: 128
  ROI_BOX_HEAD:
    POOLER_TYPE: "ROIAlignRotated"
    BBOX_REG_WEIGHTS: (1,1,1,1,1) #Another option to try: (10.0, 10.0, 5.0, 5.0, 10.0) 
  PROPOSAL_GENERATOR:
    NAME: "RRPN"
  RPN:
    HEAD_NAME: "StandardRPNHead"
    BBOX_REG_WEIGHTS: (1,1,1,1,1) #Another option to try: (10, 10, 5, 5, 1)
  ANCHOR_GENERATOR:
    NAME: "RotatedAnchorGenerator"
    ANGLES: [[-90,-60,-30,0,30,60,90]]
  BACKBONE:
    FREEZE_AT: 5

SOLVER:
  BASE_LR: 0.0002
  CHECKPOINT_PERIOD: 3000
  IMS_PER_BATCH: 2
  MAX_ITER: 150000
  STEPS: (100000, 130000)
  AMP:
    ENABLED: true
TEST:
  AUG:
    ENABLED: false
  EVAL_PERIOD: 1000